### ISSUE TITLE
ENCRYPTION_KEY\" not set in config

### ISSUE THREAD

**Issue by brayan1991** [trustenterprises/hedera-serverless-api#37]
I am getting the following error when attempting any POST:  {"errors":"Unable to process encryption action, 32 character length \"ENCRYPTION_KEY\" not set in config"}. Any Ideas?

**Comment by mattsmithies** [comment]
This is a good catch, I've updated the docs to help understand the meaning of the **ENCRYPTION_KEY** environment variable. https://docs.trust.enterprises/deployment/environment-variables

**Comment by mattsmithies** [comment]
Closing issue, as it was fixed with a documentation update
