### ISSUE TITLE
Cannot create new NFT collection on testnet (due to invalid royalty account)

### ISSUE THREAD

**Issue by 8Beesfr** [trustenterprises/hedera-serverless-api#48]
Hey Matt! I'm unable to create new NFT collections on testnet - looking in the error log it shows me "receipt for transaction 0.0.0@1676468433.835305033 contained error status INVALID_CUSTOM_FEE_COLLECTOR"
This makes me assume that the account ID of your testnet acc is not existing anymore after the testnet reset :)

**Comment by mattsmithies** [comment]
lol, thanks mate!

**Comment by 8Beesfr** [comment]
Long Live The Testnet Reset! Hurray hurray! :(

**Comment by mattsmithies** [comment]
https://github.com/trustenterprises/hedera-serverless-api/commit/7536c9daa5337d43c1ebd15ee82806bf764d62ce
